version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: actions
      POSTGRES_PASSWORD: actions
      POSTGRES_DB: actions
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: ../backend
    environment:
      DATABASE_URL: postgres://actions:actions@db:5432/actions
      PORT: 4000
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_REPOS: ${GITHUB_REPOS}
      POLL_INTERVAL_SECONDS: ${POLL_INTERVAL_SECONDS:-60}
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL}
      ALERT_EMAIL_TO: ${ALERT_EMAIL_TO}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SECURE: ${SMTP_SECURE}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      FRONTEND_ORIGIN: http://localhost:5173
    depends_on:
      - db
    ports:
      - "4000:4000"

  web:
    build: ../frontend
    environment:
      VITE_API_URL: http://localhost:4000
    depends_on:
      - api
    ports:
      - "5173:80"

volumes:
  db-data: 