name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: actions
          POSTGRES_PASSWORD: actions
          POSTGRES_DB: actions
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U actions -d actions"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=10

    env:
      DATABASE_URL: postgres://actions:actions@localhost:5432/actions
      NODE_ENV: test

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Backend install
        working-directory: backend
        run: npm ci

      - name: Backend lint
        working-directory: backend
        run: npm run lint --if-present

      - name: Backend tests
        working-directory: backend
        run: npm test --if-present

      - name: Frontend install
        working-directory: frontend
        run: npm ci

      - name: Frontend build
        working-directory: frontend
        run: npm run build

      - name: Build docker images
        run: |
          docker build -t dashboard-backend:ci ./backend
          docker build -t dashboard-frontend:ci ./frontend
